### ISSUE TITLE
Large amount of false subscriptions

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkySubscriptions#3]
I got a large amount of subscriptions I didnt manually create.
Could this be a unwanted effect of the "connect with minecraft account"-feature?

![image](https://user-images.githubusercontent.com/58751503/132009586-b960dcc7-518d-4470-9379-a480bb6345e5.png)

**Comment by Ekwav** [comment]
This was an issue in the old system where mc-connect would create a subscription to get notified.
